cookie:
  expiry_days: 30
  key: some_random_signature_key_12345
  name: inventory_cookie
credentials:
  usernames:
    LLEEL:
      email: testX@gmail.com
      name: test1XX
      password: $2b$12$pvowXZ0aNJWqzaaNJM0IQ.c/z7U4k3KojqViWZ30rkF6hm2eplICq
      role: admin
    admin:
      email: admin@example.com
      name: NOMBRE TEST
      password: $2b$12$7WkKRpP3ViXPJR8DUPO2/OqvewlX/YEVrGi4cnCtlE6bSuMF/PJJG
      role: admin
    user:
      email: user@example.com
      name: Regular User
      password: $2b$12$aHV.eHz3A4HwsFVBX5nYTezyY8Q2Xoj.I4.Ey31gkLBU.ZEkcb6Za
      role: user
